### ISSUE TITLE
Add ability to deploy metadata

### ISSUE THREAD

**Issue by kjonescertinia** [apex-dev-tools/benchmarker#10]
When writing performance tests its sometimes useful to be able to deploy code to run on an org. This is fairly easy to do via the jsforce connection but it would be nice if the benchmarker provided some helpers to do this.

**Comment by pwrightcertinia** [comment]
[git-ops](https://github.com/apex-dev-tools/git-ops/blob/4f3fbe37a20e3ce69656039ef8041eaba61793da/src/tracking.ts#L113) (should have been called source-ops) has a deploy example, plenty of redundant stuff in there but otherwise it is quite easy to set up for single file deploys.
