### ISSUE TITLE
Add failure retry mechanism to connection.replaceClasses

### ISSUE THREAD

**Issue by kjonescertinia** [apex-dev-tools/benchmarker#12]

**Comment by pwrightcertinia** [comment]
See [the current implementation](https://github.com/apex-dev-tools/benchmarker/blob/3aa9a56e4926067257b3a716f23316abce4ada29/src/services/salesforce/utils.ts#L277) and [a usage](https://github.com/apex-dev-tools/benchmarker/blob/3aa9a56e4926067257b3a716f23316abce4ada29/src/services/org.ts#L21)
